config:
  name: Handbag2
  process:
  - datasets:
    - cache_latents_to_disk: true
      caption_dropout_rate: 0.05
      caption_ext: txt
      folder_path: training_data
      resolution:
      - 1024
      shuffle_tokens: true
    device: cuda:0
    model:
      assistant_lora_path: ostris/FLUX.1-schnell-training-adapter
      is_flux: true
      name_or_path: black-forest-labs/FLUX.1-schnell
      quantize: true
    network:
      linear: 16
      linear_alpha: 16
      type: lora
    performance_log_every: 1000
    sample:
      guidance_scale: 1
      height: 1024
      neg: ''
      prompts:
      - prompt1
      - prompt2
      sample_every: 200
      sample_steps: 4
      sampler: flowmatch
      seed: 42
      walk_seed: true
      width: 1024
    save:
      dtype: float16
      max_step_saves_to_keep: 4
      push_to_hub: false
      save_every: 200
    train:
      batch_size: 1
      dtype: bf16
      ema_config:
        ema_decay: 0.99
        use_ema: true
      gradient_accumulation_steps: 1
      gradient_checkpointing: true
      lr: 1e-4
      noise_scheduler: flowmatch
      optimizer: adamw8bit
      steps: 2000
      train_text_encoder: false
      train_unet: true
    training_folder: output/Handbag_fashion
    trigger_word: H-1
    type: sd_trainer
job: extension
meta:
  name: '[name]'
  version: '1.0'

